version: '3.8'

services:
  smallprox:
    build: .
    container_name: smallprox
    ports:
      - "5000:5000"  # Modifica la porta se necessario
    environment:
      - PASS=password
    restart: unless-stopped
